workflows:
  intel-linux-build:
    name: Spiderling Intel Mac
    # 这里定义运行环境，Codemagic 默认支持多任务
    instance_type: mac_mini_m2

    environment:
      vars:
        PYTHON_VERSION: 3.10

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
    scripts:
      - name: Setup Python
        script: |
          brew install python@3.10
          python --version

      - name: Install dependencies
        script: |
          brew install binutils
          
          pip install \
                  PyQt5 \
                  SQLAlchemy \
                  pandas \
                  numpy \
                  beautifulsoup4 \
                  selenium \
                  webdriver-manager \
                  openpyxl \
                  pymysql \
                  pymssql \
                  psycopg2 \
                  cryptography \
                  lxml \
                  pyinstaller
      - name: Inject Version
        script: |
          VERSION=${CM_TAG:-"manual"}
          echo "__version__ = '$VERSION'" > services/version_info.py
      - name: Build Mac Intel Executable
        script: |
          # export PATH="/opt/homebrew/opt/binutils/bin:$PATH"
          # export MACOSX_DEPLOYMENT_TARGET=10.15
          arch -x86_64 pyinstaller --windowed --onedir --noconfirm --icon="assets/logo.icns" \
          --target-architecture x86_64  \
          --add-data "config:config" \
          --add-data "assets:assets" \
          --collect-all psycopg2 \
          --collect-all pymssql \
          --collect-all cryptography \
          --hidden-import="psycopg2" \
          --hidden-import="pymssql" \
          --hidden-import="selenium" \
          --hidden-import="webdriver-manager" \
          --hidden-import="selenium.webdriver.chrome.webdriver" \
          spiderling.py
          
          brew install create-dmg
          create-dmg --volname "Spiderling-$VERSION" --window-size 600 400 --icon-size 100 --icon "spiderling.app" 175 120 --app-drop-link 425 120 "spiderling-macos-x86_64-$VERSION.dmg" "dist/spiderling.app"
    artifacts:
      - "*.dmg"
